### ISSUE TITLE
Crash when loading a heavy combo in checker

### ISSUE THREAD

**Issue by cris840** [lociero/League-of-Legends-Accounts-Creator#14]
When loading a combo of 500,000 lines or more, the application becomes slow and when checking the application stops working after a while. Leaving that aside, as a suggestion you can add a button that allows to hide and show the accounts that are banned or with failed auth, also the option to export proxies, combos that work in user: pass format and on the other hand also export accounts that they work with your information. His checker is fast and has a lot of potential. Nice job

**Comment by lociero** [comment]
@cris840 thank you for feedback, I decided to disable checker for some time. First of all it was never meant to crack accounts, so even if I will enable it again, such amount of accounts will not be allowed. Good luck =)
