### ISSUE TITLE
wacatac?

### ISSUE THREAD

**Issue by hckowalhc-pl** [lociero/League-of-Legends-Accounts-Creator#15]
![wacatac](https://user-images.githubusercontent.com/78986264/107827868-ebdbdf80-6d87-11eb-87a4-4e784165bc08.png)

**Comment by Conflictino** [comment]
that’s scary

**Comment by lociero** [comment]
false positive

**Comment by lociero** [comment]
I will change the comparing version method, I guess this false positive is all about downloading remote file from the internet, in this case its just a `package.json` from the same repository. reopened issue.
