### ISSUE TITLE
Future Request: Add Authentication Proxy

### ISSUE THREAD

**Issue by muratulashozturk** [lociero/League-of-Legends-Accounts-Creator#16]
Hi, Is it possible to add authenticated proxy support for proxies? (**IP:PORT:USER:PASS**)
Also can you please try to add HTTP support for proxies by using this package? **[https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)**
Thanks.

**Comment by lociero** [comment]
@muratulashozturk Hello, I will add auth proxies for sure, but what about http(s).. its a head-scratcher, I was trying to use this package and it breaks event loop or something, some promises just never fulfill with that, also I tried to use built in http proxies feature in axios but here is another problem, only 1 / 100 proxies are working, and every time its a different one so you are not able to make a success request to riot api... Idk =)

**Comment by muratulashozturk** [comment]
Well, what about this? have you ever tried. [superagent-proxy](https://www.npmjs.com/package/superagent-proxy)

**Comment by lociero** [comment]
@muratulashozturk I tried a lot of things, this included =)
