### ISSUE TITLE
CAPTCHA_NETWORK_ERROR

### ISSUE THREAD

**Issue by shinozunas** [lociero/League-of-Legends-Accounts-Creator#24]
when i click on  START CREATION ,it says "CAPTCHA_NETWORK_ERROR" in the ERRORS barre
![Capture d’écran 2021-09-25 152716](https://user-images.githubusercontent.com/68299761/134774962-b01c0f5e-d476-491e-bf9c-dffa0f0b6a36.png)

**Comment by lociero** [comment]
@shinozunas Hello, check your captcha balance

**Comment by lociero** [comment]
@pewucz yes, and u need positive balance to solve the captchas.
