### ISSUE TITLE
Please help with this problem my work depends on it  it was working fine :(

### ISSUE THREAD

**Issue by JimCarry455** [lociero/League-of-Legends-Accounts-Creator#27]
I am receiving captcha network error however my api balance is positive (1.99) it was working fine for the last two days idk what happened i am using the old version 
![captha](https://user-images.githubusercontent.com/91767827/142717297-14b38275-2fd0-4657-ae7d-c040389be031.png)
 and when i try to use the new version i receive a new error displayed on the second photo
![error](https://user-images.githubusercontent.com/91767827/142717311-ad0419c0-3e20-4752-a3c0-6c915b8b56cc.png)

**Comment by lociero** [comment]
@JimCarry455 Hello, what captcha service are u using? And if its not hard, copy full error text and send it here please.

**Comment by JimCarry455** [comment]
i am using 2 captcha and it was working fine the full error text : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/> <title>405 - HTTP verb used to access this page is not allowed.</title> <style type="text/css">  </style> </head> <body> <div id="header"><h1>Server Error</h1></div> <div id="content"> <div class="content-container"><fieldset> <h2>405 - HTTP verb used to access this page is not allowed.</h2> <h3>The page you are looking for cannot be displayed because an invalid method (HTTP verb) was used to attempt access.</h3> </fieldset></div> </div> </body> </html>

**Comment by lociero** [comment]
Can u contact me on discord? megaded#1529
2Captcha works just fine on my side, I cant reproduce the bug and this response is not documented
