### ISSUE TITLE
CAPTCHA_INVALID_TOKEN/ERROR_CAPTCHA_UNSOLVABLE

### ISSUE THREAD

**Issue by Nutimsss** [lociero/League-of-Legends-Accounts-Creator#61]
I tested multiple times, not a single time worked (2captcha) 
![image](https://github.com/lociero/League-of-Legends-Accounts-Creator/assets/135927221/cd9050a9-2498-4e47-afac-427725e480ae)

**Comment by lociero** [comment]
@Nutimsss Hello.
I did create a ticket on 2captcha and waiting for their response, they are ignoring for the moment. 2captcha is not working properly, capmonster is recommended.

**Comment by dng-nguyn** [comment]
![image](https://github.com/lociero/League-of-Legends-Accounts-Creator/assets/133786254/7c735b30-800b-46a5-afa3-65b41129a833)
same thing happens for capsolver, only 2 out of 10 accounts is generated
