### ISSUE TITLE
CAPTCHA_INVALID_TOKEN

### ISSUE THREAD

**Issue by terracentric** [lociero/League-of-Legends-Accounts-Creator#62]
i use the new version and  capsolver  api,after create 10 accounts,it gave me CAPTCHA_INVALID_TOKEN,i wonder why

**Comment by lociero** [comment]
@terracentric i wonder why too. capsolver support is ignoring for the moment. it doesnt work properly. capmonster is recommended and its cheaper.

**Comment by terracentric** [comment]
thanks,i will try capmonster

**Comment by terracentric** [comment]
i  try capmonster,and i met RQDATA_REQUEST_FAILED,SIGN_UP_API_ERROR,Could you kindly provide some advice on how to delicately handle this situation that has arisen?

**Comment by lociero** [comment]
@terracentric you should not use the free proxies. Read the readme please and buy some iproyal residential proxies (recommended ones)

**Comment by terracentric** [comment]
thanks
