### ISSUE TITLE
Unsolvable / CAPTCHA Timeout on Capmonster - 

### ISSUE THREAD

**Issue by Nullsec0** [lociero/League-of-Legends-Accounts-Creator#63]
![image](https://github.com/lociero/League-of-Legends-Accounts-Creator/assets/140753984/061f338f-2c68-4580-b2eb-f7c4de54655e)
`CAPTCHA Unsolvable / CAPTCHA timeout on Capmonster when generating new accounts.

**Comment by lociero** [comment]
@Nullsec0 Hello.

Capmonster is not working for the moment. We are waiting for the fix on their side. Try capsolver please.

**Comment by UsernameLuxi** [comment]
I have tried 2captcha and capmonster cloud, and none of them works. What is going on?
