### ISSUE TITLE
CAPTCHA_INVALID_TOKEN

### ISSUE THREAD

**Issue by szanellato93** [lociero/League-of-Legends-Accounts-Creator#65]
I downloaded the latest release and configured. I'm using the captcha resolver 2captcha, the api key is correct because i can retrieve my balance. 

When i try create an account, I receive always this error:

![errorjpg](https://github.com/lociero/League-of-Legends-Accounts-Creator/assets/15063799/6b077765-f8ab-4e3f-9316-a67c5265ed7a)

**Comment by lociero** [comment]
@szanellato93 Hello. 2/rucaptcha do not support hcaptcha enterprise, you have to use different captcha solver.
