### ISSUE TITLE
Generate EXE file, open exe and display blank

### ISSUE THREAD

**Issue by yan454983448** [lociero/League-of-Legends-Accounts-Creator#7]
Generate EXE file, open exe and display blank

**Comment by yan454983448** [comment]
![111](https://user-images.githubusercontent.com/73240833/97879101-8759bf00-1d5a-11eb-8a91-fbc2a95aaebc.JPG)

**Comment by lociero** [comment]
@yan454983448 Hello, I just found out that randomly messed up the building script, react-scripts somehow disappeared from dependencies, I pushed an update, should be fine right now. Answer pls if its working now =)

**Comment by yan454983448** [comment]
@lociero It can be used normally. Thank you very much

**Comment by lociero** [comment]
@yan454983448 Glad I helped =)
