### ISSUE TITLE
agency channels

### ISSUE THREAD

**Issue by eness-1** [lociero/League-of-Legends-Accounts-Creator#8]
Can you provide agency channels in Japan or the Philippines? The software agency does not have these two regions, nor does it support local agency

**Comment by eness-1** [comment]
thanks

**Comment by lociero** [comment]
@eness-1 Hey, I will add later an option, so u can manually add ur own proxy list, right now I'm using proxyscrape, they dont provide proxies from these countries, i'm sorry, right now u can use only ur local ip for JP server. I will try to implement this as fast as i can, when i will have enough free time =)
